using System.IO;
using System.Security.Cryptography;
using System.Windows.Media.Imaging;

namespace BeeX.DeskNest;

public sealed partial class DeskNestService
{
    void PollClipboard(){try{var captures=State.Nests.Where(x=>x.Kind==NestKind.Capture).ToList();if(captures.Count==0)return;if(System.Windows.Clipboard.ContainsFileDropList()){var files=System.Windows.Clipboard.GetFileDropList().Cast<string>().Where(IsSupportedClipboardImage).ToList();if(files.Count>0){var signature=ClipboardFileSignature(files);if(signature==lastClipboardFileSignature)return;lastClipboardFileSignature=signature;Directory.CreateDirectory(ClipboardImageDirectory);foreach(var source in files){var extension=Path.GetExtension(source).ToLowerInvariant();var destination=UniqueImagePath(ClipboardImageDirectory,"BeeX_Clipboard",extension);File.Copy(source,destination);foreach(var n in captures){n.Captures.Insert(0,new CaptureItem{Text=extension==".gif"?"剪貼板 GIF":"剪貼板圖片",ImagePath=destination,Source="Clipboard"});TrimCaptures(n);if(windows.TryGetValue(n.Id,out var w))w.RefreshData();}}Save();return;}}if(System.Windows.Clipboard.ContainsImage()){var image=System.Windows.Clipboard.GetImage();if(image!=null){image=NormalizeClipboardImage(image);using var memory=new MemoryStream();var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(image));encoder.Save(memory);var bytes=memory.ToArray();var hash=Convert.ToHexString(SHA256.HashData(bytes));if(hash!=lastClipboardImageHash){lastClipboardImageHash=hash;Directory.CreateDirectory(ClipboardImageDirectory);var path=UniqueImagePath(ClipboardImageDirectory,"BeeX_Clipboard");File.WriteAllBytes(path,bytes);foreach(var n in captures){n.Captures.Insert(0,new CaptureItem{Text="剪貼板圖片",ImagePath=path,Source="Clipboard"});TrimCaptures(n);if(windows.TryGetValue(n.Id,out var w))w.RefreshData();}Save();}}return;}if(!System.Windows.Clipboard.ContainsText())return;var text=System.Windows.Clipboard.GetText();if(string.IsNullOrWhiteSpace(text)||text==lastClipboard)return;lastClipboard=text;foreach(var n in captures){if(n.Captures.FirstOrDefault()?.Text==text)continue;n.Captures.Insert(0,new CaptureItem{Text=text,Source="Clipboard"});TrimCaptures(n);if(windows.TryGetValue(n.Id,out var w))w.RefreshData();}Save();}catch{}}
    static BitmapSource NormalizeClipboardImage(BitmapSource image){var converted=new FormatConvertedBitmap(image,System.Windows.Media.PixelFormats.Bgra32,null,0);var stride=converted.PixelWidth*4;var pixels=new byte[stride*converted.PixelHeight];converted.CopyPixels(pixels,stride,0);var anyAlpha=false;for(var i=3;i<pixels.Length;i+=4)if(pixels[i]!=0){anyAlpha=true;break;}if(!anyAlpha)for(var i=3;i<pixels.Length;i+=4)pixels[i]=255;var normalized=BitmapSource.Create(converted.PixelWidth,converted.PixelHeight,converted.DpiX,converted.DpiY,System.Windows.Media.PixelFormats.Bgra32,null,pixels,stride);normalized.Freeze();return normalized;}
    void TrimCaptures(NestModel nest){var limit=(int)Math.Clamp(State.CaptureLimit,20,500);if(nest.Captures.Count>limit)nest.Captures.RemoveRange(limit,nest.Captures.Count-limit);}
    static string UniqueImagePath(string directory,string prefix,string extension=".png"){var stamp=DateTime.Now.ToString("yyyyMMdd_HHmmss_fff");var path=Path.Combine(directory,$"{prefix}_{stamp}{extension}");var suffix=1;while(File.Exists(path))path=Path.Combine(directory,$"{prefix}_{stamp}_{suffix++}{extension}");return path;}
    static bool IsSupportedClipboardImage(string path)=>File.Exists(path)&&new[]{".gif",".png",".jpg",".jpeg",".bmp",".webp"}.Contains(Path.GetExtension(path),StringComparer.OrdinalIgnoreCase);
    static string ClipboardFileSignature(IEnumerable<string> files)=>string.Join("|",files.Select(path=>{var info=new FileInfo(path);return $"{Path.GetFullPath(path).ToUpperInvariant()}:{info.Length}:{info.LastWriteTimeUtc.Ticks}";}));
    public bool CopyCaptureToClipboard(CaptureItem item){try{var imagePath=item.ImagePath;if(string.IsNullOrWhiteSpace(imagePath)&&item.Text.StartsWith("[截圖] ",StringComparison.Ordinal)){var legacyPath=item.Text[5..].Trim();if(File.Exists(legacyPath)){imagePath=legacyPath;item.ImagePath=legacyPath;item.Text="螢幕截圖";Save();}}if(!string.IsNullOrWhiteSpace(imagePath)&&File.Exists(imagePath)){var image=new BitmapImage();image.BeginInit();image.CacheOption=BitmapCacheOption.OnLoad;image.UriSource=new Uri(imagePath,UriKind.Absolute);image.EndInit();image.Freeze();using var memory=new MemoryStream();var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(image));encoder.Save(memory);lastClipboardImageHash=Convert.ToHexString(SHA256.HashData(memory.ToArray()));if(Path.GetExtension(imagePath).Equals(".gif",StringComparison.OrdinalIgnoreCase)){var fullPath=Path.GetFullPath(imagePath);lastClipboardFileSignature=ClipboardFileSignature(new[]{fullPath});var data=new System.Windows.DataObject();var files=new System.Collections.Specialized.StringCollection{fullPath};data.SetFileDropList(files);data.SetImage(image);System.Windows.Clipboard.SetDataObject(data,true);}else System.Windows.Clipboard.SetImage(image);return true;}if(string.IsNullOrEmpty(item.Text))return false;System.Windows.Clipboard.SetText(item.Text);lastClipboard=item.Text;return true;}catch{return false;}}
}
