using System.Windows;
using System.Windows.Input;
using MouseEventArgs=System.Windows.Input.MouseEventArgs;
using DragEventArgs=System.Windows.DragEventArgs;
using DragDropEffects=System.Windows.DragDropEffects;
using Grid=System.Windows.Controls.Grid;
using Button=System.Windows.Controls.Button;
using Image=System.Windows.Controls.Image;
using Orientation=System.Windows.Controls.Orientation;
using Border=System.Windows.Controls.Border;
using StackPanel=System.Windows.Controls.StackPanel;
using TextBlock=System.Windows.Controls.TextBlock;
using RowDefinition=System.Windows.Controls.RowDefinition;
using ColumnDefinition=System.Windows.Controls.ColumnDefinition;

namespace BeeX.DeskNest;
public partial class ControlWindow : Window
{
    readonly DeskNestService service; bool ready;Border? controlRoot;Grid? controlBody;System.Windows.Controls.Primitives.UniformGrid? toolGrid;System.Windows.Point toolDragStart;Button? toolDragButton;
    public ControlWindow(DeskNestService service) { InitializeComponent();this.service=service;ConfigureTransparentChrome();SourceInitialized+=(_,_)=>ApplyPreferences();var tools=controlBody?.Children.OfType<System.Windows.Controls.Primitives.UniformGrid>().FirstOrDefault();if(tools!=null){toolGrid=tools;tools.AllowDrop=true;tools.PreviewMouseLeftButtonDown+=ToolGrid_MouseLeftButtonDown;tools.PreviewMouseMove+=ToolGrid_MouseMove;tools.Drop+=ToolGrid_Drop;var weather=new Button{Content=BuildToolButtonContent("Weather"),Tag="Weather"};weather.Click+=(_,_)=>service.Add(NestKind.Weather);var tags=new Button{Content=BuildToolButtonContent("Tags"),Tag="Tags"};tags.Click+=(_,_)=>service.Add(NestKind.Tags);var monitor=new Button{Content=BuildToolButtonContent("SystemMonitor"),Tag="SystemMonitor"};monitor.Click+=(_,_)=>service.Add(NestKind.SystemMonitor);tools.Children.Add(weather);tools.Children.Add(tags);tools.Children.Add(monitor);ApplyToolOrder();AdaptToolGrid();}StartupCheck.IsChecked=service.State.StartWithWindows;RefreshShortcutTooltips();ready=true;Closing+=(_,e)=>{e.Cancel=true;Hide();};MaximizeRestore.Attach(this); }
    void ConfigureTransparentChrome(){controlBody=(Grid)Content;Content=null;WindowStyle=WindowStyle.None;AllowsTransparency=true;Background=System.Windows.Media.Brushes.Transparent;controlBody.Background=System.Windows.Media.Brushes.Transparent;var shell=new Grid();shell.RowDefinitions.Add(new RowDefinition{Height=new GridLength(TitleBarMetrics.Dip(this))});shell.RowDefinitions.Add(new RowDefinition());var title=new Grid{Margin=new Thickness(14,0,8,0)};title.ColumnDefinitions.Add(new ColumnDefinition());title.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var brand=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};brand.Children.Add(new Image{Source=new System.Windows.Media.Imaging.BitmapImage(new Uri("pack://application:,,,/Assets/BeeX.png")),Width=20,Height=20});brand.Children.Add(new TextBlock{Text="BeeX DeskNest",Margin=new Thickness(8,0,0,0),VerticalAlignment=VerticalAlignment.Center,FontWeight=FontWeights.SemiBold});title.Children.Add(brand);var actions=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};var minimize=new Button{Content="−",Width=40,Height=40,Padding=new Thickness(0),Background=System.Windows.Media.Brushes.Transparent,ToolTip=Localization.T("最小化",service.State.Language)};minimize.Click+=(_,_)=>WindowState=WindowState.Minimized;var close=new Button{Content="×",Width=40,Height=40,Padding=new Thickness(0),Background=System.Windows.Media.Brushes.Transparent,ToolTip=Localization.T("關閉",service.State.Language)};close.Click+=(_,_)=>Hide();actions.Children.Add(minimize);actions.Children.Add(close);Grid.SetColumn(actions,1);title.Children.Add(actions);title.MouseLeftButtonDown+=(_,e)=>{if(InputHitTestHelper.IsInteractive(e.OriginalSource as DependencyObject))return;if(e.LeftButton==MouseButtonState.Pressed)DragMove();};shell.Children.Add(title);Grid.SetRow(controlBody,1);shell.Children.Add(controlBody);controlRoot=new Border{CornerRadius=new CornerRadius(service.State.CornerRadius),BorderBrush=new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromArgb(90,255,138,0)),BorderThickness=new Thickness(1),ClipToBounds=true,Child=shell};Content=controlRoot;System.Windows.Shell.WindowChrome.SetWindowChrome(this,new System.Windows.Shell.WindowChrome{ResizeBorderThickness=new Thickness(7),CaptionHeight=0,CornerRadius=new CornerRadius(service.State.CornerRadius),GlassFrameThickness=new Thickness(0),UseAeroCaptionButtons=false});}
    protected override void OnContentRendered(EventArgs e){base.OnContentRendered(e);EnsureDateTools();Localization.Apply(this,service.State.Language);RefreshShortcutTooltips();RefreshFeatures();WindowRegionHelper.StyleCaptionButtons(this);WindowRegionHelper.ApplyDeferred(this,service.State.CornerRadius);WindowRegionHelper.AddResizeHitTest(this,42);System.Windows.Controls.ScrollViewer.SetVerticalScrollBarVisibility(NestList,System.Windows.Controls.ScrollBarVisibility.Visible);System.Windows.Controls.ScrollViewer.SetHorizontalScrollBarVisibility(NestList,System.Windows.Controls.ScrollBarVisibility.Disabled);}
    void EnsureDateTools(){if(controlBody?.Children.OfType<System.Windows.Controls.Primitives.UniformGrid>().FirstOrDefault() is not { } tools)return;if(!tools.Children.OfType<Button>().Any(x=>x.Tag?.ToString()=="Countdown")){var countdown=new Button{Content=BuildToolButtonContent("Countdown"),Tag="Countdown"};countdown.Click+=(_,_)=>service.Add(NestKind.Countdown);tools.Children.Add(countdown);}if(!tools.Children.OfType<Button>().Any(x=>x.Tag?.ToString()=="Launcher")){var launcher=new Button{Content=BuildToolButtonContent("Launcher"),Tag="Launcher"};launcher.Click+=(_,_)=>service.Add(NestKind.Launcher);tools.Children.Add(launcher);}if(!tools.Children.OfType<Button>().Any(x=>x.Tag?.ToString()=="WorkTimer")){var work=new Button{Content=BuildToolButtonContent("WorkTimer"),Tag="WorkTimer"};work.Click+=(_,_)=>service.Add(NestKind.WorkTimer);tools.Children.Add(work);}if(!tools.Children.OfType<Button>().Any(x=>x.Tag?.ToString()=="CollapseAll")){var fold=new Button{Content=BuildToolButtonContent("CollapseAll"),Tag="CollapseAll"};fold.Click+=(_,_)=>service.ToggleCollapseAll();tools.Children.Add(fold);}if(!tools.Children.OfType<Button>().Any(x=>x.Tag?.ToString()=="WindowTransparency")){var wt=new Button{Content=BuildToolButtonContent("WindowTransparency"),Tag="WindowTransparency"};wt.Click+=(_,_)=>service.ShowWindowTransparency();tools.Children.Add(wt);}if(!tools.Children.OfType<Button>().Any(x=>x.Tag?.ToString()=="Cleaner")){var cleaner=new Button{Content=BuildToolButtonContent("Cleaner"),Tag="Cleaner"};cleaner.Click+=(_,_)=>service.ShowCleaner();tools.Children.Add(cleaner);}if(!tools.Children.OfType<Button>().Any(x=>x.Tag?.ToString()=="Translate")){var translate=new Button{Content=BuildToolButtonContent("Translate"),Tag="Translate"};translate.Click+=(_,_)=>service.CaptureScreenForTranslation();tools.Children.Add(translate);}EnsureEasterEggButton();ApplyToolOrder();AdaptToolGrid();}
    /// <summary>彩蛋解鎖後在工具按鈕區生成遊戲入口（幂等，未解鎖不顯示）</summary>
    public void EnsureEasterEggButton(){if(!service.State.EasterEggUnlocked||toolGrid==null)return;if(toolGrid.Children.OfType<Button>().Any(x=>x.Tag?.ToString()=="EasterEgg"))return;var egg=new Button{Content=BuildToolButtonContent("EasterEgg"),Tag="EasterEgg"};egg.Click+=(_,_)=>service.StartEasterEgg();toolGrid.Children.Add(egg);ApplyToolOrder();AdaptToolGrid();}
    protected override void OnRenderSizeChanged(SizeChangedInfo sizeInfo){base.OnRenderSizeChanged(sizeInfo);AdaptToolGrid();WindowRegionHelper.ApplyDeferred(this,service.State.CornerRadius);}
    protected override void OnPreviewMouseLeftButtonDown(MouseButtonEventArgs e){base.OnPreviewMouseLeftButtonDown(e);if(e.ClickCount!=1||e.GetPosition(this).Y>TitleBarMetrics.Dip(this)||InputHitTestHelper.IsInteractive(e.OriginalSource as DependencyObject))return;e.Handled=true;DragMove();}
    /// <summary>跨螢幕拖動後 DPI 變化，重算標題欄物理 65px 對應的邏輯高度</summary>
    protected override void OnDpiChanged(DpiScale oldDpi,DpiScale newDpi){base.OnDpiChanged(oldDpi,newDpi);if(controlRoot?.Child is Grid shell&&shell.RowDefinitions.Count>0)shell.RowDefinitions[0].Height=new GridLength(TitleBarMetrics.Dip(this));}
    
    public void RefreshList() => NestList.ItemsSource = service.State.Nests.Select(n => new { Model = n, Title=Localization.DisplayTitle(n,service.State.Language), Icon = SvgIcon.Load(n.Kind switch { NestKind.Note=>"note",NestKind.Todo=>"checklist",NestKind.Capture=>"camera",NestKind.Music=>"music",NestKind.Clock=>"clock",NestKind.ManagedFiles=>"archive",NestKind.Screenshot=>"screenshot",NestKind.Weather=>"sun",NestKind.Tags=>"tag",NestKind.SystemMonitor=>"cpu",NestKind.Deadline=>"calendar",NestKind.Countdown=>"calendar",NestKind.Launcher=>"rocket",NestKind.WorkTimer=>"alarm",_=>"star" },24,new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(255,138,0))), Subtitle = Localization.T(n.IsVisible ? "顯示在桌面" : "目前已隱藏",service.State.Language), ToggleText=Localization.T("顯示 / 隱藏",service.State.Language), DeleteText=Localization.T("刪除",service.State.Language), ToggleIcon=SvgIcon.Load(n.IsVisible?"eye":"eye",14,new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(13,19,33))), DeleteIcon=SvgIcon.Load("trash",14,new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(180,35,24))) }).ToList();
    public void RefreshLanguage(){RefreshList();Localization.Apply(this,service.State.Language);RefreshShortcutTooltips();if(ArrangeLayoutText!=null)ArrangeLayoutText.Text=Localization.T("整理布局",service.State.Language);if(SettingsText!=null)SettingsText.Text=Localization.T("設定",service.State.Language);if(ClearAllText!=null)ClearAllText.Text=Localization.T("清除全部",service.State.Language);}
    string ToolButtonIconName(string key)=>key switch{"Note"=>"pencil","Todo"=>"checklist","MapFolder"=>"folder","Managed"=>"archive","CaptureFolder"=>"screenshot","QuickNote"=>"camera","Music"=>"music","Clock"=>"clock","Screenshot"=>"screenshot","ToggleAll"=>"eye","Weather"=>"sun","Tags"=>"tag","SystemMonitor"=>"cpu","Countdown"=>"calendar","Launcher"=>"rocket","WorkTimer"=>"alarm","CollapseAll"=>"chevron-down","WindowTransparency"=>"aspect-ratio","Cleaner"=>"sparkles","Translate"=>"world","EasterEgg"=>"player-play",_=>"star"};
    string ToolButtonText(string key)=>key switch{"Note"=>Localization.T("便箋",service.State.Language),"Todo"=>Localization.T("待辦",service.State.Language),"MapFolder"=>Localization.T("映射資料夾",service.State.Language),"Managed"=>Localization.T("收納格子",service.State.Language),"CaptureFolder"=>Localization.T("截圖文件夾",service.State.Language),"QuickNote"=>Localization.T("隨記",service.State.Language),"Music"=>Localization.T("音樂",service.State.Language),"Clock"=>Localization.T("時鐘",service.State.Language),"Screenshot"=>Localization.T("立即截圖",service.State.Language),"ToggleAll"=>Localization.T("顯示／隱藏全部",service.State.Language),"Weather"=>Localization.T("天氣",service.State.Language),"Tags"=>Localization.T("標籤",service.State.Language),"SystemMonitor"=>Localization.T("系統監控",service.State.Language),"Countdown"=>Localization.T("日程倒數",service.State.Language),"Launcher"=>Localization.T("快速啟動",service.State.Language),"WorkTimer"=>Localization.T("上下班提醒",service.State.Language),"CollapseAll"=>Localization.T("折疊／展開",service.State.Language),"WindowTransparency"=>Localization.T("視窗透明",service.State.Language),"Cleaner"=>Localization.T("系統清理",service.State.Language),"Translate"=>Localization.T("翻譯",service.State.Language),"EasterEgg"=>Localization.T("蜂巢彩蛋",service.State.Language),_=>key};
    object BuildToolButtonContent(string key,System.Windows.Media.Brush? iconBrush=null){var text=ToolButtonText(key);var panel=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};var icon=new Image{Source=SvgIcon.Load(ToolButtonIconName(key),16,iconBrush??Foreground as System.Windows.Media.Brush),Width=16,Height=16,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(0,0,6,0)};panel.Children.Add(icon);panel.Children.Add(new TextBlock{Text=text,VerticalAlignment=VerticalAlignment.Center});return panel;}
    void RefreshToolButtonTexts(System.Windows.Controls.Primitives.UniformGrid tools){foreach(var button in tools.Children.OfType<System.Windows.Controls.Button>()){var key=button.Tag?.ToString();if(!string.IsNullOrWhiteSpace(key))button.Content=BuildToolButtonContent(key,button.Foreground);}}
    public void RefreshShortcutTooltips(){if(controlBody is not Grid root)return;var tools=root.Children.OfType<System.Windows.Controls.Primitives.UniformGrid>().FirstOrDefault();if(tools==null)return;RefreshToolButtonTexts(tools);var shortcutLabel=Localization.T("快捷鍵",service.State.Language);var unsetLabel=Localization.T("未設定（可在設定頁配置）",service.State.Language);foreach(var button in tools.Children.OfType<System.Windows.Controls.Button>()){var key=button.Tag?.ToString();if(string.IsNullOrEmpty(key))continue;var shortcut=service.State.Hotkeys.GetValueOrDefault(key,"");var label=ToolButtonText(key);button.ToolTip=string.IsNullOrWhiteSpace(shortcut)?$"{label}\n{shortcutLabel}：{unsetLabel}":$"{label}\n{shortcutLabel}：{shortcut}";}ShortcutHint.Text="";ShortcutHint.Visibility=Visibility.Collapsed;}
    string DisplayShortcut(string value)=>string.IsNullOrWhiteSpace(value)?Localization.T("未設定（可在設定頁配置）",service.State.Language):value;
    public void RefreshFeatures(){if(controlBody is not Grid root)return;var tools=root.Children.OfType<System.Windows.Controls.Primitives.UniformGrid>().FirstOrDefault();if(tools==null)return;ApplyToolOrder();foreach(var button in tools.Children.OfType<System.Windows.Controls.Button>()){var key=button.Tag?.ToString()??"";var userVisible=!service.State.ToolButtonVisibility.TryGetValue(key,out var visible)||visible;button.Visibility=userVisible?Visibility.Visible:Visibility.Collapsed;}AdaptToolGrid();}
    void AdaptToolGrid(){if(toolGrid==null)return;var visible=toolGrid.Children.OfType<UIElement>().Count(x=>x.Visibility==Visibility.Visible);var width=Math.Max(1,ActualWidth-80);var columns=width>=1120?5:width>=860?4:width>=650?3:2;toolGrid.Columns=columns;toolGrid.Rows=Math.Max(1,(int)Math.Ceiling(visible/(double)columns));}
    void ApplyToolOrder(){if(toolGrid==null||service.State.ToolButtonOrder.Count==0)return;var children=toolGrid.Children.OfType<Button>().ToList();foreach(var button in children)toolGrid.Children.Remove(button);foreach(var key in service.State.ToolButtonOrder){var b=children.FirstOrDefault(x=>x.Tag?.ToString()==key);if(b!=null){toolGrid.Children.Add(b);children.Remove(b);}}foreach(var b in children)toolGrid.Children.Add(b);}
    void SaveToolOrder(){if(toolGrid==null)return;service.State.ToolButtonOrder=toolGrid.Children.OfType<Button>().Select(x=>x.Tag?.ToString()).Where(x=>!string.IsNullOrWhiteSpace(x)).Cast<string>().ToList();service.Save();}
    void ToolGrid_MouseLeftButtonDown(object sender,MouseButtonEventArgs e){toolDragStart=e.GetPosition(this);toolDragButton=VisualTreeUtils.FindParent<Button>(e.OriginalSource as DependencyObject);}
    void ToolGrid_MouseMove(object sender,MouseEventArgs e){if(e.LeftButton!=MouseButtonState.Pressed||toolDragButton==null)return;var p=e.GetPosition(this);if(Math.Abs(p.X-toolDragStart.X)<6&&Math.Abs(p.Y-toolDragStart.Y)<6)return;DragDrop.DoDragDrop(toolDragButton,toolDragButton.Tag?.ToString()??"",DragDropEffects.Move);}
    void ToolGrid_Drop(object sender,DragEventArgs e){if(toolGrid==null||!e.Data.GetDataPresent(System.Windows.DataFormats.StringFormat))return;var key=e.Data.GetData(System.Windows.DataFormats.StringFormat)?.ToString();if(string.IsNullOrWhiteSpace(key))return;var source=toolGrid.Children.OfType<Button>().FirstOrDefault(x=>x.Tag?.ToString()==key);var target=VisualTreeUtils.FindParent<Button>(e.OriginalSource as DependencyObject);if(source==null||target==null||ReferenceEquals(source,target))return;var children=toolGrid.Children.Cast<UIElement>().ToList();var sourceIndex=children.IndexOf(source);var targetIndex=children.IndexOf(target);if(sourceIndex<0||targetIndex<0)return;(children[sourceIndex],children[targetIndex])=(children[targetIndex],children[sourceIndex]);toolGrid.Children.Clear();foreach(var child in children)toolGrid.Children.Add(child);SaveToolOrder();AdaptToolGrid();}
    public void ApplyPreferences(){var state=service.State;var dark=state.Theme=="Dark";var honey=state.Theme=="Honey";var alpha=(byte)Math.Clamp(state.WidgetOpacity*255,0,255);var uniform=dark?System.Windows.Media.Color.FromArgb(alpha,13,19,33):honey?System.Windows.Media.Color.FromArgb(alpha,255,244,222):System.Windows.Media.Color.FromArgb(alpha,245,247,250);var panelAlpha=(byte)Math.Clamp(state.WidgetOpacity*36,0,48);var panel=System.Windows.Media.Color.FromArgb(panelAlpha,255,255,255);Background=System.Windows.Media.Brushes.Transparent;if(controlRoot!=null){controlRoot.Background=new System.Windows.Media.SolidColorBrush(uniform);controlRoot.CornerRadius=new CornerRadius(state.CornerRadius);}if(controlBody!=null)controlBody.Background=System.Windows.Media.Brushes.Transparent;Foreground=ContrastHelper.TextFor(new System.Windows.Media.SolidColorBrush(uniform),dark?System.Windows.Media.Brushes.White:new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(13,19,33)));Resources["ControlPrimary"]=Foreground;Resources["ControlSecondary"]=new System.Windows.Media.SolidColorBrush(dark?System.Windows.Media.Color.FromRgb(198,205,218):System.Windows.Media.Color.FromRgb(107,114,128));Resources["ControlSurface"]=new System.Windows.Media.SolidColorBrush(panel);Resources["ControlLine"]=new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromArgb(dark?(byte)54:(byte)34,255,255,255));FontSize=service.InterfaceFontSize();Localization.ApplyFont(this,service.InterfaceFontFamily(),service.InterfaceFontSize());if(System.Windows.PresentationSource.FromVisual(this)!=null)AcrylicHelper.Apply(this,state.Theme=="Acrylic",state.WidgetOpacity,dark);WindowRegionHelper.StyleCaptionButtons(this);ApplyBottomButtonIcons();ApplyCaptureButtonColor(dark);}
    void ApplyCaptureButtonColor(bool dark){if(toolGrid==null)return;var b=toolGrid.Children.OfType<Button>().FirstOrDefault(x=>x.Tag?.ToString()=="CaptureFolder");if(b==null)return;b.Background=new System.Windows.Media.SolidColorBrush(dark?System.Windows.Media.Color.FromRgb(43,60,99):System.Windows.Media.Color.FromRgb(13,19,33));}
    void ApplyBottomButtonIcons(){var accent=new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(255,138,0));var navy=new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(13,19,33));if(ArrangeLayoutIcon!=null)ArrangeLayoutIcon.Source=SvgIcon.Load("layout",14,navy);if(SettingsIcon!=null)SettingsIcon.Source=SvgIcon.Load("settings",14,navy);if(ClearAllIcon!=null)ClearAllIcon.Source=SvgIcon.Load("trash",14,new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(180,35,24)));}
    void AddNote_Click(object s, RoutedEventArgs e) => service.Add(NestKind.Note);
    void AddTodo_Click(object s, RoutedEventArgs e) => service.Add(NestKind.Todo);
    void AddFolder_Click(object s, RoutedEventArgs e) => service.AddFolder();
    void AddManaged_Click(object s, RoutedEventArgs e) => service.AddManagedFiles();
    void AddCapture_Click(object s, RoutedEventArgs e) => service.Add(NestKind.Capture);
    void AddMusic_Click(object s, RoutedEventArgs e) => service.Add(NestKind.Music);
    void AddClock_Click(object s, RoutedEventArgs e) => service.Add(NestKind.Clock);
    void OpenCaptures_Click(object s, RoutedEventArgs e) => service.OpenCaptureFolder();
    void CaptureNow_Click(object s, RoutedEventArgs e) => service.CaptureScreen();
    void ToggleAll_Click(object s, RoutedEventArgs e) => service.ToggleAll();
    void Toggle_Click(object s, RoutedEventArgs e) => service.Toggle((NestModel)((FrameworkElement)s).Tag);
    void Delete_Click(object s, RoutedEventArgs e) { var n = (NestModel)((FrameworkElement)s).Tag; if (BeeXDialog.Confirm(this,Localization.T("刪除格子",service.State.Language),Localization.Format("確定刪除「{0}」？資料夾中的檔案不會被刪除。",service.State.Language,Localization.DisplayTitle(n,service.State.Language)),service.State)) service.Remove(n); }
    void Startup_Changed(object s, RoutedEventArgs e) { if (ready) service.SetStartup(StartupCheck.IsChecked == true); }
    void Settings_Click(object s,RoutedEventArgs e)=>service.ShowSettings();
    void ArrangeLayout_Click(object s,RoutedEventArgs e)=>service.ArrangeDesktopLayout();
    void ClearAll_Click(object s,RoutedEventArgs e){if(BeeXDialog.Confirm(this,Localization.T("清除全部",service.State.Language),Localization.T("確定清除所有格子與隨記資料？收納和映射資料夾中的原始檔案不會刪除。",service.State.Language),service.State,Localization.T("清除全部",service.State.Language)))service.ClearAll();}
    void NestList_MouseMove(object s,MouseEventArgs e){if(VisualTreeUtils.FindParent<Button>(e.OriginalSource as DependencyObject)!=null)return;if(e.LeftButton==MouseButtonState.Pressed&&NestList.SelectedItem is not null){dynamic row=NestList.SelectedItem;DragDrop.DoDragDrop(NestList,(NestModel)row.Model,DragDropEffects.Move);}}
    void NestList_DoubleClick(object s,MouseButtonEventArgs e){if(VisualTreeUtils.FindParent<Button>(e.OriginalSource as DependencyObject)!=null)return;if(NestList.SelectedItem is not null){dynamic row=NestList.SelectedItem;service.SetVisible((NestModel)row.Model,true);}}
    void NestList_Drop(object s,DragEventArgs e){if(!e.Data.GetDataPresent(typeof(NestModel)))return;var item=(NestModel)e.Data.GetData(typeof(NestModel));var pos=e.GetPosition(NestList);var target=NestList.InputHitTest(pos) as DependencyObject;while(target is not null&&target is not System.Windows.Controls.ListBoxItem)target=System.Windows.Media.VisualTreeHelper.GetParent(target);var index=target is System.Windows.Controls.ListBoxItem li?NestList.ItemContainerGenerator.IndexFromContainer(li):service.State.Nests.Count;service.Reorder(item,index);}
}
